name = "nodewarden"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# KV Namespace for storing vault data
[[kv_namespaces]]
binding = "VAULT"
id = "36ac5efd1b2147e395e01a3b795971a0"

# R2 Bucket for storing attachments
[[r2_buckets]]
binding = "ATTACHMENTS"
bucket_name = "nodewarden-attachments"
